# Bibliotecas

In [3]:
import os

import numpy as np

import pandas as pd

import keras
from keras.datasets import cifar10

import numpy as np
import matplotlib.pyplot as plt
import skimage
from skimage.io import imread, imsave, imshow
from skimage.measure import label, regionprops
from skimage import restoration, filters
from skimage.color import rgb2gray
from skimage import img_as_ubyte
from skimage.segmentation import clear_border
from skimage.color import label2rgb

from PIL import Image
import math

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

### Verificando se tem mais de uma label nas imagens

In [22]:
result_images = list()
path = "../../images_th_mean_4/"
dirs = os.listdir(path)

for item in dirs:
    if os.path.isfile(path + item):
        # print(path + item)
        label_image = label(imread(path + item))
        print(len(label_image))

512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512

### Deixando as imagens apenas com as bordas

In [50]:
path = "../../images_th_mean_4/"
new_folder = "../../images_border/"
dirs = os.listdir(path)

for item in dirs:
    if os.path.isfile(path + item):

        contorno_roberts = filters.roberts(imread(path + item, as_gray=True))
        os.makedirs(path, exist_ok=True)
        imsave(new_folder+'image_border_{}'.format((item[:-4])[-15:]), img_as_ubyte(contorno_roberts), check_contrast=False)

In [70]:
def calcula_histograma(img):
    # convertendo a imagem em array numpy
    img = np.asarray(img)
    print(len(img))

    # achatando a matriz em array 1D
    flat = img.flatten()
    print(len(flat))
    
    # coletando o histograma com a função numpy
    histogram, bin_edges = np.histogram(img, bins=256, range=(0, 256))
    return histogram


path = "../../images_border/"
dirs = os.listdir(path)

for item in dirs:
    if os.path.isfile(path + item):

        img = imread(path + item, as_gray=True)
        aux = calcula_histograma(img)
        print(aux[0])
        print(aux[1])
        break

512
349184
348472
0

In [5]:
data_frame = pd.read_csv(
    "/home/pedroazevedo141/repositories/predict_ovinos/TCC/Assets/only_pesovivo_second_name.csv", sep=',')

In [6]:
data_frame['second_name'] = data_frame['second_name'].astype(int)
data_frame = data_frame.sort_values(by='second_name')
data_frame

,second_name,Rebanho,Data da coleta,Animal,AOL,POL,COL,EGS,ECC,PESOVIVO,PESOABATE,RC,FAMACHA,CC,AG,AC,AP,CT,CP,Profund
11,1,Ricardo,02/02/2022,AMARELO,NaN,NaN,NaN,NaN,"2,5",38.50,NaN,NaN,NaN,65.0,57.0,56.0,32.0,77.0,42.0,24.0
2,2,Ricardo,15/12/2021,AMARELO,"7,98","2,51","4,45","4,9","2,5",45.20,"19,6","43,36",NaN,79.0,71.0,74.0,40.0,85.0,35.0,34.0
16,3,Ricardo,12/03/2022,Animal 1,"8,5","2,18","4,33","1,99","2,5",41.20,NaN,NaN,2.0,64.0,71.0,72.0,44.0,80.0,41.0,28.0
17,4,Ricardo,12/03/2022,Animal 2,"8,3","2,22","4,12","2,83","3,5",45.00,NaN,NaN,2.0,70.0,69.0,72.0,37.0,92.0,43.0,35.0
18,5,Ricardo,12/03/2022,Animal 3,"8,2","1,99","4,97","3,01","2,5",40.75,NaN,NaN,1.0,68.0,71.0,73.0,40.0,81.0,43.0,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,59,Ricardo,02/02/2022,ROXO,NaN,NaN,NaN,NaN,3,48.50,NaN,NaN,NaN,74.0,67.0,69.0,35.0,87.0,43.0,34.0
12,60,Ricardo,02/02/2022,VERDE,NaN,NaN,NaN,NaN,2,39.80,NaN,NaN,NaN,73.0,69.0,66.0,36.0,80.0,41.0,30.0
6,61,Ricardo,15/12/2021,VERMELHO,"7,88","2,23","4,26","1,7",2,34.95,"15,2","43,49",NaN,58.0,70.0,67.0,35.0,74.0,37.0,32.0
7,62,Ricardo,15/12/2021,VERMELHO+AZUL,"10,02","2,47","4,93","2,11","2,5",42.20,"19,6","46,45",NaN,64.0,62.0,61.0,28.0,81.0,42.0,33.0
9,63,Ricardo,02/02/2022,VERMELHO,NaN,NaN,NaN,NaN,"3,5",39.75,NaN,NaN,NaN,77.0,69.0,70.0,36.0,85.0,41.0,34.0

In [7]:
data_frame['second_name'][0]

55

In [34]:
aux_list = list()
for item in dirs:
    if os.path.isfile(path + item):
        aux_list.append(path + item)

In [37]:
aux_list.sort()
print(aux_list)

['../../images_border/image_border__amarelo_15.png', '../../images_border/image_border__laranja_15.png', '../../images_border/image_border__r_vermelho.png', '../../images_border/image_border_age_r_preto.png', '../../images_border/image_border_age_r_verde.png', '../../images_border/image_border_e_r_amarelo.png', '../../images_border/image_border_e_r_azul_15.png', '../../images_border/image_border_e_r_roxo_15.png', '../../images_border/image_border_ge_r_branco.png', '../../images_border/image_border_lho_azul_15.png', '../../images_border/image_border_mage_r_azul.png', '../../images_border/image_border_mage_r_roxo.png', '../../images_border/image_border_r_animal_01.png', '../../images_border/image_border_r_animal_02.png', '../../images_border/image_border_r_animal_03.png', '../../images_border/image_border_r_animal_04.png', '../../images_border/image_border_r_animal_05.png', '../../images_border/image_border_r_animal_06.png', '../../images_border/image_border_r_animal_07.png', '../../images_border/image_border_r_animal_08.png', '../../images_border/image_border_r_animal_09.png', '../../images_border/image_border_r_animal_10.png', '../../images_border/image_border_r_animal_11.png', '../../images_border/image_border_r_animal_12.png', '../../images_border/image_border_r_animal_13.png', '../../images_border/image_border_r_animal_14.png', '../../images_border/image_border_r_animal_15.png', '../../images_border/image_border_r_animal_16.png', '../../images_border/image_border_r_animal_17.png', '../../images_border/image_border_r_animal_18.png', '../../images_border/image_border_r_animal_19.png', '../../images_border/image_border_r_animal_20.png', '../../images_border/image_border_r_animal_21.png', '../../images_border/image_border_r_animal_22.png', '../../images_border/image_border_r_animal_23.png', '../../images_border/image_border_r_animal_24.png', '../../images_border/image_border_r_animal_25.png', '../../images_border/image_border_r_animal_26.png', '../../images_border/image_border_r_animal_27.png', '../../images_border/image_border_r_animal_28.png', '../../images_border/image_border_r_animal_29.png', '../../images_border/image_border_r_animal_30.png', '../../images_border/image_border_r_animal_31.png', '../../images_border/image_border_r_animal_45.png', '../../images_border/image_border_r_animal_46.png', '../../images_border/image_border_r_animal_47.png', '../../images_border/image_border_r_animal_48.png', '../../images_border/image_border_r_animal_49.png', '../../images_border/image_border_r_animal_50.png', '../../images_border/image_border_r_animal_51.png', '../../images_border/image_border_r_animal_52.png', '../../images_border/image_border_r_animal_53.png', '../../images_border/image_border_r_animal_54.png', '../../images_border/image_border_r_animal_55.png', '../../images_border/image_border_r_animal_56.png', '../../images_border/image_border_r_animal_57.png', '../../images_border/image_border_r_animal_58.png', '../../images_border/image_border_r_animal_59.png', '../../images_border/image_border_r_animal_60.png', '../../images_border/image_border_r_branco_15.png', '../../images_border/image_border_r_grande_15.png', '../../images_border/image_border_vermelho_15.png']

In [38]:
path = "../../images_border/"
dirs = os.listdir(path)
count = 0

data = {}

for item in aux_list:
    if count == 0:
        img = np.asarray(imread(item, as_gray=True))
        flat = img.flatten()
        
        for value in range(len(flat)):
            data.update({value:flat[value]})
        
        data.update({len(flat): data_frame['PESOVIVO'][(count)]})
        
        df_img = pd.DataFrame(data, index=[0])
    else:
        img = np.asarray(imread(item, as_gray=True))
        flat = img.flatten()

        for value in range(len(flat)):
            data.update({value: flat[value]})

        data.update({len(flat): data_frame['PESOVIVO'][(count)]})

        df2 = pd.DataFrame(data, index=[0])
        df_img = pd.concat([df_img, df2])
    
    count += 1

In [46]:
df_img

,0,1,2,3,4,5,6,7,8,9,...,349175,349176,349177,349178,349179,349180,349181,349182,349183,349184
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,38.00
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,25.20
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,45.20
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,41.95
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,41.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,42.30
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,43.20
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,38.10
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,37.60
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,42.70

In [152]:
# len(df_img["349184"][0])

### Modelos de predição

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score


def pred_randomForestRegressor(X, y):
    """
    X é uma matriz onde cada linha corresponde aos atributos calculados com o descritor
    y são os rótulos da classe de cada imagem. Exemplo [0,1,0,0,1,2,2,0,0,0,...,1]
    """
    # separar conjuntos de treino e teste
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

    # Fit the model
    model = RandomForestRegressor()
    model = model.fit(X_train, y_train)

    importance = model.feature_importances_

    plt.bar([x for x in range(len(importance))], importance)

    plt.xticks([x for x in range(len(importance))],
               X.columns.values.tolist(), rotation=30)
    plt.show()

    y_test_predict = model.predict(X_test)

    plt.scatter(y_test-y_test_predict, y_test_predict)

    plt.show()

    # model evaluation for training set
    y_train_predict = model.predict(X_train)

    rmse_train = (np.sqrt(mean_squared_error(y_train, y_train_predict)))
    r2_train = r2_score(y_train, y_train_predict)

    print(f"RMSE for training is {rmse_train}")
    print(f"R2 score for training is {r2_train}")

    # model evaluation for training set
    y_test_predict = model.predict(X_test)

    rmse_test = (np.sqrt(mean_squared_error(y_test, y_test_predict)))
    r2_test = r2_score(y_test, y_test_predict)

    print(f"RMSE for testing is {rmse_test}")
    print(f"R2 score for testing is {r2_test}")

    from sklearn import metrics
    print('Mean Absolute Error:',
          metrics.mean_absolute_error(y_test, y_test_predict))
    print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_test_predict))
    print('Root Mean Squared Error:', np.sqrt(
        metrics.mean_squared_error(y_test, y_test_predict)))

    return pd.DataFrame({'Actual': y_test, 'Predicted': y_test_predict})

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from pprint import pprint
from sklearn.model_selection import RandomizedSearchCV


def pred_RandomizedSearchCV(X, y):
    """
        X é uma matriz onde cada linha corresponde aos atributos calculados com o descritor
        y são os rótulos da classe de cada imagem. Exemplo [0,1,0,0,1,2,2,0,0,0,...,1]
        """

    # Number of trees in random forest
    n_estimators = [int(x)
                    for x in np.linspace(start=200, stop=2000, num=10)]
    # Number of features to consider at every split
    max_features = ['auto', 'sqrt']
    # Maximum number of levels in tree
    max_depth = [int(x) for x in np.linspace(10, 110, num=11)]
    max_depth.append(None)
    # Minimum number of samples required to split a node
    min_samples_split = [2, 5, 10]
    # Minimum number of samples required at each leaf node
    min_samples_leaf = [1, 2, 4]
    # Method of selecting samples for training each tree
    bootstrap = [True, False]
    # Create the random grid
    random_grid = {'n_estimators': n_estimators,
                   'max_features': max_features,
                   'max_depth': max_depth,
                   'min_samples_split': min_samples_split,
                   'min_samples_leaf': min_samples_leaf,
                   'bootstrap': bootstrap}
    pprint(random_grid)

    # separar conjuntos de treino e teste
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, train_size=0.7)

    # Use the random grid to search for best hyperparameters
    # First create the base model to tune
    rf = RandomForestRegressor()
    # Random search of parameters, using 3 fold cross validation,
    # search across 100 different combinations, and use all available cores
    model = RandomizedSearchCV(estimator=rf, param_distributions=random_grid,
                               n_iter=100, cv=3, verbose=2, random_state=42, n_jobs=-1)
    # Fit the random search model
    model.fit(X_train, y_train)

    y_test_predict = model.predict(X_test)

    plt.scatter(y_test-y_test_predict, y_test_predict)

    plt.show()

    # model evaluation for training set
    y_train_predict = model.predict(X_train)

    rmse_train = (np.sqrt(mean_squared_error(y_train, y_train_predict)))
    r2_train = r2_score(y_train, y_train_predict)

    print(f"RMSE for training is {rmse_train}")
    print(f"R2 score for training is {r2_train}")

    # model evaluation for training set
    y_test_predict = model.predict(X_test)

    rmse_test = (np.sqrt(mean_squared_error(y_test, y_test_predict)))
    r2_test = r2_score(y_test, y_test_predict)

    print(f"RMSE for testing is {rmse_test}")
    print(f"R2 score for testing is {r2_test}")

    from sklearn import metrics
    print('Mean Absolute Error:', metrics.mean_absolute_error(
        y_test, y_test_predict))
    print('Mean Squared Error:', metrics.mean_squared_error(
        y_test, y_test_predict))
    print('Root Mean Squared Error:', np.sqrt(
        metrics.mean_squared_error(y_test, y_test_predict)))

    return pd.DataFrame({'Actual': y_test, 'Predicted': y_test_predict})

In [57]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics

def pred_linearRegression(X, y):
    """
    X é uma matriz onde cada linha corresponde aos atributos calculados com o descritor
    y são os rótulos da classe de cada imagem. Exemplo [0,1,0,0,1,2,2,0,0,0,...,1]
    """
    # separar conjuntos de treino e teste
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)
    # criar instancia do classificador
    model = LinearRegression(fit_intercept=True, n_jobs=1000, copy_X=True, positive=True)

    model = model.fit(X_train, y_train)

    importance = model.coef_
    
    plt.bar([x for x in range(len(importance))], importance)

    plt.xticks([x for x in range(len(importance))], X.columns.values.tolist(), rotation=30)
    
    plt.show()
    
    y_test_predict = model.predict(X_test)
    
    plt.scatter(y_test-y_test_predict, y_test_predict)

    plt.show()
    
    # model evaluation for training set
    y_train_predict = model.predict(X_train)

    rmse_train = (np.sqrt(mean_squared_error(y_train, y_train_predict)))
    r2_train = r2_score(y_train, y_train_predict)

    print(f"RMSE for training is {rmse_train}")
    print(f"R2 score for training is {r2_train}")
    
    # model evaluation for training set
    y_test_predict = model.predict(X_test)

    rmse_test = (np.sqrt(mean_squared_error(y_test, y_test_predict)))
    r2_test = r2_score(y_test, y_test_predict)

    print(f"RMSE for testing is {rmse_test}")
    print(f"R2 score for testing is {r2_test}")
    
    print(model.intercept_)
    
    y_pred = model.predict(X_test)
    
    print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
    print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
    print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

    return pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

In [47]:
X = df_img.drop(349184, axis=1)
y = df_img[349184]

In [49]:
y

0    38.00
0    25.20
0    45.20
0    41.95
0    41.90
     ...
0    42.30
0    43.20
0    38.10
0    37.60
0    42.70
Name: 349184, Length: 62, dtype: float64

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.5)

In [99]:
# criar instancia do classificador
model = LinearRegression(fit_intercept=True, n_jobs=100000)

model = model.fit(X_train, y_train)

In [100]:
# model evaluation for training set
y_train_predict = model.predict(X_train)

In [101]:
rmse_train = (np.sqrt(mean_squared_error(y_train, y_train_predict)))
r2_train = r2_score(y_train, y_train_predict)

print(f"RMSE for training is {rmse_train}")
print(f"R2 score for training is {r2_train}")

RMSE for training is 2.352280398246779e-14
R2 score for training is 1.0

In [102]:
# model evaluation for training set
y_pred = model.predict(X_test)

rmse_test = (np.sqrt(mean_squared_error(y_test, y_pred)))
r2_test = r2_score(y_test, y_pred)

print(f"RMSE for testing is {rmse_test}")
print(f"R2 score for testing is {r2_test}")

RMSE for testing is 8.176065200022283
R2 score for testing is -0.030335885573010257

In [103]:
print(model.intercept_)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(
    metrics.mean_squared_error(y_test, y_pred)))

pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

38.39866184095984
Mean Absolute Error: 5.078289153845763
Mean Squared Error: 66.8480421550154
Root Mean Squared Error: 8.176065200022283

   Actual  Predicted
0   74.60  38.406071
0   34.00  38.187456
0   42.20  38.488708
0   34.90  38.362430
0   34.60  38.299989
0   37.90  38.242824
0   39.10  38.440261
0   42.20  38.343423
0   36.00  38.291273
0   45.30  38.438181
0   38.30  38.485679
0   38.50  38.417340
0   47.55  38.510784
0   32.00  37.883708
0   40.75  38.384760
0   46.75  38.409211
0   29.00  38.206936
0   43.10  38.262344
0   32.85  38.083911
0   48.50  38.412062
0   28.70  38.196871
0   32.75  38.185868
0   37.00  38.626776
0   39.20  38.455587
0   38.00  37.879941
0   45.25  38.494019
0   42.30  38.153606
0   37.60  38.374544
0   41.95  38.490119
0   41.20  38.352948
0   39.75  38.261935